name: davidkelber
favicon: null
layout_spectrum: 0.90099
typography_spectrum: 0.8670556750148535
title: Project Genesis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b0b0b'
    - '#8b860b'
    - '#0b8b7b'
    - '#3c0b8b'
    - '#0b688b'
  brandStrength: 0.6875
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 0.22542249923571944
purpose: []
