name: davidkelber
favicon: null
layout_spectrum: 0.4506610326934606
typography_spectrum: 0.8670556750148535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7334239121992141
  lightness: 0.910222084261477
  saturation: 0.604944635881111
  rhythmicContrast: 0.22542249923571944
purpose: []
